# Generated by Django 2.2.14 on 2020-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20200906_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pcp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
