# Generated by Django 2.2.14 on 2020-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20201117_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pvp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
