# Generated by Django 2.2.14 on 2020-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('documento', models.IntegerField(choices=[(0, 'CEDULA'), (1, 'RUC')], default=0)),
                ('numero_documento', models.CharField(max_length=13, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-nombres', '-numero_documento', '-direccion'],
                'verbose_name_plural': 'proveedores',
                'verbose_name': 'proveedor',
                'db_table': 'proveedor',
            },
        ),
    ]
