# Generated by Django 2.2.14 on 2020-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (0, 'Femenino')], default=1)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-nombres', '-apellidos', '-cedula'],
                'verbose_name_plural': 'clientes',
                'verbose_name': 'cliente',
                'db_table': 'cliente',
            },
        ),
    ]
