# Generated by Django 2.2.14 on 2020-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20200905_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
