# Generated by Django 2.2.14 on 2020-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-nombre', '-descripcion'],
                'verbose_name_plural': 'cargos',
                'verbose_name': 'cargo',
                'db_table': 'cargo',
            },
        ),
    ]
