# Generated by Django 2.2.14 on 2020-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id', '-nombre', '-descripcion'],
                'verbose_name_plural': 'categorias',
                'verbose_name': 'categoria',
                'db_table': 'categoria',
            },
        ),
    ]
