# Generated by Django 2.2.14 on 2020-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_indice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='indice',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=9),
        ),
    ]
